// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Use process.env directly to avoid Prisma's strict env() requirement during generate
const directUrl = process.env.DIRECT_URL || process.env.DATABASE_URL || "";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use direct URL for migrations, bypassing the connection pooler
    // Falls back to DATABASE_URL or empty string for prisma generate
    url: directUrl,
  },
});
